name: dart_climate
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Thiago Soares Figueiredo <thiagosf.dev@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  dialog: ^0.7.0

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
